default: &default
  pool: 5

development:
  <<: *default
  adapter: sqlite3
  timeout: 5000
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>